(function(){
  const current=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const links={english:['english.html','🔤🌈','Tiếng Anh'],vocab:['vocabulary-list.html','↳','Vocabulary List'],math:['math.html','➕','Toán'],addsub:['cong-tru-10.html','↳','Cộng Trừ Phạm Vi 10'],compare:['so-sanh.html','↳','So sánh'],shapes:['hinh-phang.html','↳','Hình phẳng'],archimedes:['toan-archimedes.html','↳','Toán Archimedes']};
  function active(p){return current===p}
  function build(){
    const nav=document.querySelector('#gradeNav, #nav, .nav'); if(!nav)return;
    const course=(href,label,icon)=>`<a href="${href}" class="${active(href)?'active':''}">${icon} ${label}</a>`;
    nav.innerHTML=`<div><button type="button" class="grade-toggle grade" data-grade="1">📂 <span>Lớp 1</span><span class="chev">⌃</span></button><div class="subnav sub open" id="shared-grade-1">${course('english.html','Tiếng Anh','🔤🌈')}<div class="course-list courses">${course('english.html','Vocabulary Games','↳')}${course('vocabulary-list.html','Vocabulary List','↳')}</div>${course('math.html','Toán','➕')}<div class="course-list courses">${course('cong-tru-10.html','Cộng Trừ Phạm Vi 10','↳')}${course('so-sanh.html','So sánh','↳')}${course('hinh-phang.html','Hình phẳng','↳')}${course('toan-archimedes.html','Toán Archimedes','↳')}</div><a href="class.html?grade=1" class="${current==='class.html'?'active':''}">📚 Các môn học</a></div></div>${Array.from({length:11},(_,i)=>{const g=i+2;return `<div><a href="class.html?grade=${g}">📁 Lớp ${g}</a></div>`}).join('')}`;
    nav.querySelector('[data-grade]')?.addEventListener('click',()=>document.getElementById('shared-grade-1')?.classList.toggle('open'));
  }
  function loadFlatShapesRuntime(){if(current!=='hinh-phang.html'||window.__flatShapesRuntime)return;const s=document.createElement('script');s.src='hinh-phang-runtime.js';s.async=false;document.body.appendChild(s)}
  function ensureFlatShapeLevels(){if(current!=='hinh-phang.html')return;const host=document.getElementById('levels');if(!host||host.children.length)return;const levels=[['1','Nhận biết hình','🔎'],['2','Hình quanh bé','🏠'],['3','Đoán theo đặc điểm','🧠'],['4','Đúng hay sai','🤔'],['5','Ghép hình','🧩'],['6','Chia hình','✂️'],['7','Đếm hình thông minh','🔢'],['8','Mảnh ghép còn thiếu','🧱'],['9','Hình mở & kín','🔓'],['10','Thử thách tổng hợp','🌟']];let selected=1;try{selected=Math.min(10,Math.max(1,Number(localStorage.getItem('flatShapeLevel')||1)))}catch(e){}host.innerHTML='';levels.forEach(([n,label,icon])=>{const b=document.createElement('button');b.type='button';b.className='choice'+(+n===selected?' on':'');b.innerHTML=`<span style="font-size:20px">${icon}</span> Level ${n}<br><small>${label}</small>`;b.addEventListener('click',()=>{selected=+n;try{localStorage.setItem('flatShapeLevel',selected)}catch(e){};host.querySelectorAll('.choice').forEach(x=>x.classList.remove('on'));b.classList.add('on')});host.appendChild(b)})}
  function init(){build();ensureFlatShapeLevels();loadFlatShapesRuntime();if(window.location.pathname.endsWith('hinh-phang.html')){const quiz=document.querySelector('#quiz');if(quiz&&typeof MutationObserver!=='undefined'){new MutationObserver(()=>{}).observe(quiz,{childList:true,subtree:true})}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
