// Cloud progress sync for the personal Learning app.
// The publishable key is intended for frontend use; database access is protected by RLS.
const SUPABASE_URL='https://ksqfcwjcijflvzzopkko.supabase.co';
const SUPABASE_KEY='sb_publishable_3WEpXJJe1HEgNJ4mfwmhUw_4jV9pQqg';
const SYNC_STORAGE='learningProgressV1';
let supabaseClient=null,syncReady=false;
function localProgress(){try{return JSON.parse(localStorage.getItem(SYNC_STORAGE)||'{}')}catch(e){return {}}}
function saveLocalProgress(p){localStorage.setItem(SYNC_STORAGE,JSON.stringify(p))}
function mergeProgress(local,cloud){const l=local||{},c=cloud||{},out={...c,...l};if((c.updated_at||'')>(l.updated_at||''))Object.assign(out,c);return out}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function ensureClient(){if(syncReady)return true;if(!window.supabase?.createClient){await loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js')}if(!window.supabase?.createClient)return false;supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);syncReady=true;return true}
async function getUser(){if(!await ensureClient())return null;return(await supabaseClient.auth.getUser()).data.user||null}
async function signInOrSignUp(email,password){await ensureClient();let r=await supabaseClient.auth.signInWithPassword({email,password});if(r.error)r=await supabaseClient.auth.signUp({email,password});return r}
async function loadCloudProgress(){if(!await ensureClient())return null;const u=await getUser();if(!u)return null;const {data,error}=await supabaseClient.from('learning_progress').select('*').eq('user_id',u.id).maybeSingle();if(error)throw error;return data}
async function saveCloudProgress(p){if(!await ensureClient())return false;const u=await getUser();if(!u)return false;const row={user_id:u.id,last_page:p.last_page||location.pathname,last_subject:p.last_subject||'',last_course:p.last_course||'',reading_story_current:Number(p.reading_story_current||1),reading_completed:p.reading_completed||p.reading_story_completed||[],reading_answers:p.reading_answers||{},math_progress:p.math_progress||{},shapes_progress:p.shapes_progress||{}};const {error}=await supabaseClient.from('learning_progress').upsert(row,{onConflict:'user_id'});if(error)throw error;return true}
async function save(patch={}){const local={...localProgress(),...patch,updated_at:new Date().toISOString()};saveLocalProgress(local);try{const u=await getUser();if(!u)return local;const cloud=await loadCloudProgress();const merged=mergeProgress(local,cloud);merged.updated_at=new Date().toISOString();saveLocalProgress(merged);await saveCloudProgress(merged);window.dispatchEvent(new CustomEvent('learningProgressSynced',{detail:merged}));return merged}catch(e){console.warn('Learning cloud sync unavailable; continuing offline.',e);return local}}
async function load(){try{const cloud=await loadCloudProgress();if(!cloud)return localProgress();const merged=mergeProgress(localProgress(),cloud);saveLocalProgress(merged);return merged}catch(e){console.warn('Could not load cloud progress.',e);return localProgress()}}
async function initLearningSync(){await ensureClient();return load()}
window.LearningSync={init:initLearningSync,signInOrSignUp,getUser,loadCloudProgress,saveCloudProgress,sync:save,save,load,getLocal:localProgress};
window.learningSync={getUser,user:getUser,signInOrSignUp,load,save,sync:save,queue:save,getLocal:localProgress};

/* Vocabulary Scramble meanings and child-friendly illustrations. */
window.VOCA_MEANINGS={
  'stand up':'đứng lên','sit down':'ngồi xuống','open':'mở','look':'nhìn','listen':'lắng nghe','happy':'vui vẻ','sad':'buồn','angry':'tức giận','hungry':'đói','tired':'mệt','scared':'sợ hãi','sunny':'có nắng','rainy':'mưa','cloudy':'nhiều mây','windy':'có gió','stormy':'có bão','hot':'nóng','cold':'lạnh','monday':'thứ Hai','tuesday':'thứ Ba','wednesday':'thứ Tư','thursday':'thứ Năm','friday':'thứ Sáu','saturday':'thứ Bảy','sunday':'Chủ nhật','one':'một','two':'hai','three':'ba','four':'bốn','five':'năm','six':'sáu','seven':'bảy','eight':'tám','nine':'chín','ten':'mười','window':'cửa sổ','door':'cửa ra vào','chair':'ghế','desk':'bàn học','bin':'thùng rác','poster':'áp phích','board':'bảng','bag':'cặp / túi','book':'sách','cupboard':'tủ','ruler':'thước kẻ','rubber':'cục tẩy','pen':'bút mực','pencil':'bút chì','red':'đỏ','yellow':'vàng','green':'xanh lá cây','pink':'hồng','purple':'tím','orange':'cam','blue':'xanh dương','black':'đen','white':'trắng','brown':'nâu','gray':'xám','mum':'mẹ','dad':'bố','grandpa':'ông','grandma':'bà','sister':'chị / em gái','brother':'anh / em trai','twin':'anh / chị / em sinh đôi','uncle':'chú / bác / cậu','auntie':'cô / dì','cousin':'anh / chị / em họ','father':'cha / bố','mother':'mẹ','parents':'bố mẹ','old':'già / lớn tuổi','young':'trẻ','tall':'cao','short':'thấp / ngắn','pretty':'xinh đẹp','handsome':'đẹp trai','he':'cậu ấy / anh ấy','she':'cô ấy / chị ấy','this':'này','is':'là','my':'của tôi','what':'cái gì','who':'ai','lion':'sư tử','duck':'con vịt','deer':'con hươu','family':'gia đình','baby':'em bé','doll':'búp bê','ball':'quả bóng','robot':'rô-bốt','boat':'thuyền','scooter':'xe trượt','skateboard':'ván trượt','kite':'diều','yoyo':'yo-yo','teddy':'gấu bông'
};
window.VOCA_EMOJI={'stand up':'🙋','sit down':'🪑','open':'📖','look':'👀','listen':'👂','happy':'😊','sad':'😢','angry':'😠','hungry':'😋','tired':'😴','scared':'😨','sunny':'☀️','rainy':'🌧️','cloudy':'☁️','windy':'💨','stormy':'⛈️','hot':'🥵','cold':'🥶','monday':'📅','tuesday':'📅','wednesday':'📅','thursday':'📅','friday':'📅','saturday':'📅','sunday':'📅','one':'1️⃣','two':'2️⃣','three':'3️⃣','four':'4️⃣','five':'5️⃣','six':'6️⃣','seven':'7️⃣','eight':'8️⃣','nine':'9️⃣','ten':'🔟','window':'🪟','door':'🚪','chair':'🪑','desk':'🖥️','bin':'🗑️','poster':'🖼️','board':'📋','bag':'🎒','book':'📚','cupboard':'🗄️','ruler':'📏','rubber':'🧽','pen':'🖊️','pencil':'✏️','red':'🔴','yellow':'🟡','green':'🟢','pink':'🩷','purple':'🟣','orange':'🟠','blue':'🔵','black':'⚫','white':'⚪','brown':'🟤','gray':'🩶','mum':'👩','dad':'👨','grandpa':'👴','grandma':'👵','sister':'👧','brother':'👦','twin':'👯','uncle':'🧔','auntie':'👩','cousin':'🧒','father':'👨','mother':'👩','parents':'👨‍👩‍👧','old':'👴','young':'🧒','tall':'🧍','short':'🧍‍♀️','pretty':'🌸','handsome':'😊','he':'👦','she':'👧','this':'👉','is':'🔗','my':'💗','what':'❓','who':'🕵️','lion':'🦁','duck':'🦆','deer':'🦌','family':'👨‍👩‍👧‍👦','baby':'👶','doll':'🪆','ball':'⚽','robot':'🤖','boat':'⛵','scooter':'🛴','skateboard':'🛹','kite':'🪁','yoyo':'🪀','teddy':'🧸'};
if(location.pathname.toLowerCase().endsWith('voca-scramble.html')){setTimeout(()=>{if(typeof window.renderQuestion==='function'&&!window.__scramblePatched){const original=window.renderQuestion;window.renderQuestion=function(){original();const q=questions?.[qi];const p=document.getElementById('picture');if(p&&q)p.textContent=window.VOCA_EMOJI[q.word]||'🔤';const m=document.getElementById('meaning');if(m&&q)m.textContent='Nghĩa: '+(window.VOCA_MEANINGS[q.word]||'');};window.__scramblePatched=true;}},0)}
