(()=>{
const TOPICS={
 'quy-luat-so':{title:'Quy luật số',icon:'🔢',desc:'Quan sát dãy số, tìm quy luật và chọn số tiếp theo.',levels:['+1','+2','−1','−2','+3','−3','xen kẽ','cộng 2 số','quy luật kép','thử thách']},
 'quy-luat-hinh':{title:'Quy luật hình',icon:'🎨',desc:'Tìm hình, màu sắc, kích thước hoặc số lượng tiếp theo.',levels:['AB','ABC','AAB','ABB','màu sắc','kích thước','số lượng','xoay hình','hai quy luật','thử thách']},
 'logic':{title:'Logic',icon:'🧩',desc:'Suy luận, loại trừ, sắp xếp và tìm điều còn thiếu.',levels:['so sánh','thứ tự','loại trừ','điều kiện','ai ở đâu','ai còn thiếu','đúng/sai','suy luận 2 bước','suy luận 3 bước','thử thách']},
 'hinh-hoc':{title:'Hình học',icon:'🔷',desc:'Nhận biết hình, đếm hình và suy luận từ đặc điểm.',levels:['nhận biết','cạnh','góc','đếm hình','phân loại','ghép hình','chia hình','quy luật hình','đếm nâng cao','thử thách']},
 'bang-so':{title:'Bảng số',icon:'📊',desc:'Điền số theo quy luật hàng, cột và ma trận.',levels:['3×3 dễ','3×3','3×3 nâng cao','hàng & cột','đường chéo','tổng bằng nhau','4×4','ma trận','ma trận kép','thử thách']},
 'khong-gian':{title:'Không gian 3D',icon:'🧊',desc:'Quan sát khối, hướng quay và cấu trúc không gian.',levels:['khối cơ bản','mặt khối','đếm khối','cao hơn','trái/phải','trước/sau','xoay','ghép khối','tưởng tượng 3D','thử thách']},
 'quan-sat':{title:'Quan sát & Đếm',icon:'🔎',desc:'Quan sát nhanh và tìm đồ vật theo điều kiện.',levels:['đếm đơn giản','màu sắc','hình dạng','đếm theo nhóm','tìm khác biệt','hai điều kiện','ba điều kiện','đếm nhanh','quan sát khó','thử thách']},
 'thu-thach':{title:'Thử thách tổng hợp',icon:'🏆',desc:'Trộn các dạng bài để bé vận dụng nhiều kỹ năng.',levels:['khởi động','dễ','dễ+','trung bình','trung bình+','khá','khá+','khó','rất khó','siêu thử thách']}
};
const $=s=>document.querySelector(s), pick=a=>a[Math.floor(Math.random()*a.length)], shuffle=a=>a.slice().sort(()=>Math.random()-.5), esc=s=>String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&bsol;','"':'&quot;'}[m]));
const key='mathThinkingProgressV1';let topic=location.pathname.match(/ttd-([\w-]+)\.html$/)?.[1]||'quy-luat-so';if(!TOPICS[topic])topic='quy-luat-so';
let level=Math.min(10,Math.max(1,Number(new URLSearchParams(location.search).get('level'))||Number(localStorage.getItem(key+'Level:'+topic))||1));let qIndex=0,score=0,streak=0,answered=false,current=null,hintUsed=false;
function rnd(n=10){return Math.floor(Math.random()*n)}
function numOptions(answer,range=12){let s=new Set([answer]);while(s.size<4){let x=Math.max(0,answer+rnd(range*2+1)-range);s.add(x)}return shuffle([...s]).map(String)}
function seq(a){return `<div class="sequence">${a.map(x=>esc(x)).join(' → ')}</div>`}
function Q(question,answer,options,visual='',explain=''){return{question,answer:String(answer),options:shuffle(options.map(String)),visual,explain}}
function makeNumber(level){
 const mode=level;
 if(mode<=2){const step=mode, start=rnd(6)+1, a=[start,start+step,start+step*2,start+step*3];return Q(`Số nào tiếp theo?`,a[3]+step,numOptions(a[3]+step,4),seq([...a,'?']),`Mỗi lần ${step===1?'thêm':'thêm'} ${step} đơn vị.`)}
 if(mode<=4){const step=mode===3?1:2,start=12+rnd(7),a=[start,start-step,start-step*2,start-step*3];return Q('Số nào còn thiếu?',a[3]-step,numOptions(a[3]-step,4),seq([a[0],a[1],a[2],'?',a[3]-step]),`Mỗi lần bớt ${step} đơn vị.`)}
 if(mode===5){const step=3,start=1+rnd(5),a=[start,start+step,start+step*2,start+step*3];return Q('Tìm số còn thiếu.',a[2]+step,numOptions(a[2]+step,5),seq([a[0],a[1],'?',a[3]]),`Dãy số tăng đều ${step} đơn vị.`)}
 if(mode===6){const step=3,start=15+rnd(5),a=[start,start-step,start-step*2,start-step*3];return Q('Số còn thiếu là số nào?',a[2]-step,numOptions(a[2]-step,5),seq([a[0],'?',a[2],a[3]]),`Dãy số giảm đều ${step} đơn vị.`)}
 if(mode===7){let a=[2,5,4,7,6,9];let start=rnd(3);a=a.map(x=>x+start);return Q('Tìm số tiếp theo theo quy luật xen kẽ.',a[5]+2,numOptions(a[5]+2,5),seq([...a,'?']),'Mỗi bước lần lượt +3, rồi −1; tiếp tục quy luật đó.')}
 if(mode===8){let a=[1+rnd(3),2+rnd(3),3+rnd(3)];let b=a[0]+a[1],c=a[1]+a[2];return Q('Số tiếp theo bằng tổng của hai số đứng trước. Số nào còn thiếu?',c+a[2],numOptions(c+a[2],6),seq([a[0],a[1],b,c,'?']),'Lấy hai số ngay trước cộng lại để được số tiếp theo.')}
 if(mode===9){let a=[1+rnd(3),3+rnd(3),6+rnd(3),10+rnd(3)];return Q('Quy luật tăng lần lượt +2, +3, +4. Số tiếp theo?',a[3]+5,numOptions(a[3]+5,6),seq([a[0],a[1],a[2],a[3],'?']),'Khoảng cách tăng thêm 1 sau mỗi bước: +2, +3, +4, +5.')}
 let a=[2+rnd(2),4+rnd(2),7+rnd(2),11+rnd(2)];return Q('Mỗi lần cộng thêm 1 đơn vị so với lần trước. Số tiếp theo?',a[3]+6,numOptions(a[3]+6,8),seq([a[0],a[1],a[2],a[3],'?']),'Hiệu lần lượt tăng: +2, +3, +4, rồi +5? Hãy quan sát kỹ: bước kế tiếp tăng thêm 1 nữa.')
}
function makePattern(level){
 const sets=[['🔴','🔵'],['🔺','🟢','⭐'],['🟡','🟡','🔵'],['🟣','🟢','🟢'],['🍎','🍌'],['🔺','🔺','⚪'],['⭐','⭐','🌙'],['⬆️','➡️','⬇️','⬅️']];let base=sets[(level-1)%sets.length],len=level<3?6:level<6?8:10;let arr=Array.from({length:len},(_,i)=>base[i%base.length]);let answer=base[len%base.length];if(level>=8){base=sets[7];arr=Array.from({length:8},(_,i)=>base[(i+level)%4]);answer=base[(8+level)%4]}let opts=[answer,...pick([['🔴','🟢','🔵','🟡'],['🔺','🟩','⭐','⚪'],['🍎','🍌','🍊','🍇'],['⬆️','➡️','⬇️','⬅️']])];opts=[answer,...shuffle(['🔴','🔵','🔺','⭐','🟢','🟡','🍎','🍌','⬆️','➡️']).filter(x=>x!==answer).slice(0,3)];return Q('Hình nào tiếp theo?',answer,opts,seq([...arr,'?']),`Các hình lặp lại theo nhóm ${base.length} hình.`)}
function makeLogic(level){
 const cases=[()=>{let a=2+rnd(3),b=a+2,c=b+2;return Q('Ba bạn có số tuổi: '+a+', '+b+', '+c+'. Ai lớn tuổi nhất?',`Bạn 3`,['Bạn 1','Bạn 2','Bạn 3','Không biết'],'👦🏻  '+a+' tuổi　👧🏻 '+b+' tuổi　🧒🏻 '+c+' tuổi','Số tuổi lớn nhất thuộc về Bạn 3.')},()=>{let names=['An','Bình','Chi'];return Q('An đứng trước Bình. Chi đứng sau Bình. Ai đứng ở giữa?', 'Bình',names,'👧 An　→　👦 Bình　→　👧 Chi','Bình nằm giữa An và Chi.')},()=>{let all=['🐶','🐱','🐰','🐟'];return Q('Hình nào không cùng nhóm với ba hình còn lại?', '🐟',all,'🐶　🐱　🐰　🐟','Ba hình đầu là động vật có thể sống trên cạn; cá sống dưới nước.')},()=>{let n=pick(['3','4','5']);return Q(`Nếu ${n} > 2 và ${n} < 6 thì câu nào đúng?`,`Số ${n} lớn hơn 2 và nhỏ hơn 6`,[`Số ${n} nhỏ hơn 2`,`Số ${n} lớn hơn 6`,`Số ${n} lớn hơn 2 và nhỏ hơn 6`,`Không thể biết`],'🔎','Cả hai điều kiện đều đúng.') }];return cases[(level-1)%cases.length]()}
function makeGeometry(level){const data=[['🔺','Hình tam giác','3 cạnh'],['🟦','Hình vuông','4 cạnh bằng nhau'],['▭','Hình chữ nhật','4 cạnh'],['⚪','Hình tròn','không có cạnh'],['⬟','Hình lục giác','6 cạnh']];if(level<=3){let d=pick(data);return Q(`Hình nào có đặc điểm: ${d[2]}?`,d[1],shuffle(data.map(x=>x[1]).slice(0,4)),d[0],`Đáp án là ${d[1]}.`)}let count=level===4?6:level===5?8:10;let triangles=rnd(Math.max(2,count-2))+2;return Q(`Có ${count} hình gồm ${triangles} hình tam giác. Số hình không phải tam giác là bao nhiêu?`,count-triangles,numOptions(count-triangles,4),`🔺`.repeat(triangles)+`　🔵`.repeat(count-triangles),'Lấy tổng số hình trừ số hình tam giác.')}
function makeGrid(level){let n=3,grid=[[1,2,3],[2,3,1],[3,1,2]];if(level>=7)n=4,grid=[[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]];let r=rnd(n),c=rnd(n),answer=grid[r][c];let cells=grid.map((row,ri)=>row.map((x,ci)=>ri===r&&ci===c?'?':x).join(' ')).join(' | ');return Q(`Điền số còn thiếu vào bảng ${n}×${n}.`,answer,numOptions(answer,n+2),`<div class="sequence">${cells}</div>`,`Mỗi hàng và mỗi cột đều đi qua các số ${n===3?'1, 2, 3':'1, 2, 3, 4'} theo cùng một quy luật.`)}
function makeSpace(level){let count=level<4?3+level:level<7?5+level:7+rnd(4);let answer=count;let visual=`<div class="cube-scene"><div class="cube" id="miniCube"><div class="face front">1</div><div class="face backf">2</div><div class="face right">3</div><div class="face left">4</div><div class="face topf">5</div><div class="face bottom">6</div></div></div><div style="font-size:18px;color:#68738a">🧊 × ${count}</div>`;return Q('Có bao nhiêu khối lập phương?',answer,numOptions(answer,3),visual,'Mỗi biểu tượng đại diện cho một khối lập phương.');}
function makeObserve(level){let colors=['🔴','🔵','🟢','🟡'];let animals=['🐶','🐱','🐰','🐼'];let arr=Array.from({length:level<4?8:12},()=>pick([...colors,...animals]));let target=level%2?pick(colors):pick(animals);if(!arr.includes(target))arr[0]=target;let answer=arr.filter(x=>x===target).length;let opts=numOptions(answer,3);return Q(`Có bao nhiêu ${target} trong hình?`,answer,opts,arr.join('　'),`Đếm đúng từng ${target}, không bỏ sót.`)}
function makeChallenge(level){let makers=[makeNumber,makePattern,makeLogic,makeGeometry,makeGrid,makeSpace,makeObserve];return makers[rnd(makers.length)](Math.max(1,level))}
function makeQuestion(){if(topic==='quy-luat-so')return makeNumber(level);if(topic==='quy-luat-hinh')return makePattern(level);if(topic==='logic')return makeLogic(level);if(topic==='hinh-hoc')return makeGeometry(level);if(topic==='bang-so')return makeGrid(level);if(topic==='khong-gian')return makeSpace(level);if(topic==='quan-sat')return makeObserve(level);return makeChallenge(level)}
function sound(ok){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A();const o=c.createOscillator(),g=c.createGain();o.type=ok?'sine':'sawtooth';o.frequency.value=ok?660:180;g.gain.value=.045;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+(ok?.18:.28))}catch(e){}}
function save(){let done=[];try{done=JSON.parse(localStorage.getItem(key+'Done:'+topic)||'[]')}catch(e){}if(score>=8&&!done.includes(level))done.push(level);try{localStorage.setItem(key+'Done:'+topic,JSON.stringify(done));localStorage.setItem(key+'Level:'+topic,String(level))}catch(e){}}
function renderLevels(){let done=[];try{done=JSON.parse(localStorage.getItem(key+'Done:'+topic)||'[]')}catch(e){}$('#levels').innerHTML=TOPICS[topic].levels.map((name,i)=>`<button class="${i+1===level?'on ':''}${done.includes(i+1)?'done':''}" data-l="${i+1}">${i+1}<br><small>${name}</small></button>`).join('');document.querySelectorAll('#levels button').forEach(b=>b.onclick=()=>{level=Number(b.dataset.l);try{localStorage.setItem(key+'Level:'+topic,String(level))}catch(e){}start()})}
function render(){current=makeQuestion();answered=false;hintUsed=false;$('#qNo').textContent=`Câu ${qIndex+1}/10`;$('#score').textContent=`⭐ ${score}`;$('#streak').textContent=`🔥 ${streak}`;$('#progress').style.width=((qIndex)/10*100)+'%';$('#question').textContent=current.question;$('#visual').innerHTML=current.visual||'';$('#options').innerHTML=current.options.map(o=>`<button class="option" data-v="${esc(o)}">${esc(o)}</button>`).join('');$('#feedback').textContent='';$('#explain').classList.remove('show');$('#explain').textContent='';$('#next').classList.remove('show');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(b,b.dataset.v));if(topic==='khong-gian'){let cube=$('#miniCube'),sx=0,sy=0,rx=-22,ry=32;if(cube)cube.onpointerdown=e=>{sx=e.clientX;sy=e.clientY;cube.setPointerCapture(e.pointerId);cube.onpointermove=ev=>{ry+=ev.clientX-sx;rx-=ev.clientY-sy;sx=ev.clientX;sy=ev.clientY;cube.style.transform=`rotateX(${rx}deg) rotateY(${ry}deg)`}}} }
function answer(btn,v){if(answered)return;const ok=String(v)===String(current.answer);if(ok){answered=true;score++;streak++;btn.classList.add('correct');document.querySelectorAll('.option').forEach(x=>x.disabled=true);$('#feedback').textContent=streak>=3?'🔥 Tuyệt vời! Chuỗi đúng '+streak+' câu!':'🎉 Chính xác!';$('#feedback').style.color='#087443';$('#explain').textContent=current.explain;$('#explain').classList.add('show');$('#next').classList.add('show');sound(true);save()}else{streak=0;btn.classList.add('wrong');$('#feedback').textContent='💪 Chưa đúng. Hãy thử lại nhé!';$('#feedback').style.color='#b4232e';if(hintUsed){$('#explain').textContent='💡 Gợi ý: '+current.explain;$('#explain').classList.add('show')}sound(false)}}
function next(){if(!answered)return;qIndex++;if(qIndex>=10){finish();return}render()}
function finish(){save();$('#progress').style.width='100%';let msg=score===10?'🏆 Hoàn hảo!':score>=8?'🌟 Rất tốt!':score>=6?'👏 Bé làm tốt!':'💪 Cố gắng thêm nhé!';$('#questionCard').innerHTML=`<div class="finish"><div class="big">${score===10?'🏆':score>=8?'🌟':'🎯'}</div><h2>${msg}</h2><p>Bé đạt <strong>${score}/10</strong> điểm ở Level ${level}.</p><p>${score>=8?'Level này đã được đánh dấu hoàn thành. Bé có thể thử Level tiếp theo!':'Hãy chơi lại Level này để cải thiện điểm số nhé.'}</p><button onclick="start()">🔄 Chơi lại</button>${level<10&&score>=8?`<button onclick="goNextLevel()">Level ${level+1} →</button>`:''}</div>`;renderLevels()}
function goNextLevel(){if(level<10){level++;start()}}
function hint(){if(answered)return;hintUsed=true;$('#explain').textContent='💡 Gợi ý: '+current.explain;$('#explain').classList.add('show')}
function start(){qIndex=0;score=0;streak=0;$('#questionCard').innerHTML='<div class="q-meta" id="qNo"></div><div class="question" id="question"></div><div class="visual" id="visual"></div><div class="options" id="options"></div><div class="feedback" id="feedback"></div><div class="actions"><button class="hint" id="hint">💡 Gợi ý</button><button class="next" id="next">Tiếp theo →</button></div><div class="explain" id="explain"></div>';$('#hint').onclick=hint;$('#next').onclick=next;renderLevels();render()}
function init(){document.title=TOPICS[topic].title+' · Toán Tư Duy Lớp 1';$('#topicIcon').textContent=TOPICS[topic].icon;$('#topicTitle').textContent=TOPICS[topic].title;$('#topicDesc').textContent=TOPICS[topic].desc;start()}
window.goNextLevel=goNextLevel;window.start=start;document.addEventListener('DOMContentLoaded',init);
})();
