(()=>{
'use strict';
const $=s=>document.querySelector(s), topic=(location.pathname.match(/ttd-(.+)\.html$/)||[])[1]||'quy-luat-so';
const META={
 'quy-luat-so':['Quy luật số','🔢','Tìm quy luật tăng, giảm, xen kẽ, thay đổi bước và quy luật kép',['+1 / −1','+2 / −2','+3 / −3','xen kẽ','bước tăng dần','bước giảm dần','cộng hai số','hai quy luật','quy luật kép','thử thách']],
 'quy-luat-hinh':['Quy luật hình','🎨','Quan sát hình dạng, màu sắc, kích thước, số lượng và hướng.',['AB','ABC','AAB / ABB','màu sắc','kích thước','số lượng','xoay hình','2 thuộc tính','quy luật kép','thử thách']],
 logic:['Suy luận logic','🧩','Sắp xếp, loại trừ và kết hợp nhiều điều kiện để tìm đáp án.',['so sánh','thứ tự','loại trừ','2 điều kiện','vị trí','đúng / sai','2 bước','3 bước','nhiều điều kiện','thử thách']],
 'hinh-hoc':['Ghép, tách & đếm hình','🔷','Đếm hình, nhận biết cấu tạo, ghép/tách và hình ẩn.',['nhận biết','số cạnh','phân loại','đếm hình','đếm nâng cao','ghép hình','tách hình','hình ẩn','nhiều bước','thử thách']],
 'bang-so':['Ma trận & bảng số','📊','Tìm ô còn thiếu bằng quy luật hàng, cột, đường chéo và ma trận hình.',['3×3 cơ bản','3×3','hàng & cột','đường chéo','tổng bằng nhau','2 quy luật','4×4','ma trận hình','ma trận kép','thử thách']],
 'khong-gian':['Không gian 3D','🧊','Đếm khối, xếp tầng, nhận biết mặt và suy luận không gian.',['khối đơn','xếp hàng','xếp tầng','khối ẩn','mặt nhìn thấy','trái / phải','trước / sau','xoay khối','ghép khối','thử thách']],
 'quan-sat':['Bài toán hình ảnh','🔎','Quan sát tranh, đếm, thêm bớt, so sánh và lọc theo điều kiện.',['đếm đồ vật','thêm / bớt','so sánh','2 loại đồ vật','2 điều kiện','3 điều kiện','sắp xếp','phần còn lại','nhiều bước','thử thách']],
 'thu-thach':['Thử thách tổng hợp','🏆','Kết hợp quy luật, logic, ma trận, hình học và không gian.',['khởi động','dễ','dễ+','trung bình','trung bình+','khá','khá+','khó','rất khó','siêu thử thách']]
};
const LEVELS=META[topic]||META['quy-luat-so'];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function rng(seed){let x=seed>>>0;return()=>{x|=0;x=x+0x6D2B79F5|0;let t=Math.imul(x^x>>>15,1|x);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const ri=(r,a,b)=>Math.floor(r()*(b-a+1))+a, pick=(r,a)=>a[ri(r,0,a.length-1)], shuffle=(r,a)=>{a=a.slice();for(let i=a.length-1;i;i--){let j=ri(r,0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
const uniq=a=>[...new Set(a.map(String))];
function choices(r,ans,delta=2,lo=0,hi=50){let a=[+ans];for(let d=1;d<=8&&a.length<4;d++){for(const v of [+ans-d*delta,+ans+d*delta,+ans-d,+ans+d])if(v>=lo&&v<=hi&&!a.includes(v)){a.push(v);if(a.length===4)break}}while(a.length<4){let v=ri(r,lo,hi);if(!a.includes(v))a.push(v)}return shuffle(r,a).map(String)}
function Q(question,answer,options,visual,explain,hint=''){options=uniq(options);if(!question||answer===undefined||!visual||!explain||options.length!==4||!options.includes(String(answer)))throw Error('invalid question');return{question,answer:String(answer),options,visual,explain,hint:hint||explain}}
const palette={red:'#ef5350',blue:'#4d8df7',green:'#34b97b',yellow:'#f4c542',purple:'#9b72e8'};
const shape={circle:(c=palette.blue)=>`<circle cx="0" cy="0" r="21" fill="${c}" stroke="#23304a" stroke-width="2.5"/>`,square:(c=palette.blue)=>`<rect x="-21" y="-21" width="42" height="42" rx="5" fill="${c}" stroke="#23304a" stroke-width="2.5"/>`,triangle:(c=palette.blue)=>`<path d="M0-24L26 22H-26Z" fill="${c}" stroke="#23304a" stroke-width="2.5"/>`,star:(c=palette.yellow)=>`<path d="M0-25L6-8L24-8L10 3L15 21L0 11L-15 21L-10 3L-24-8L-6-8Z" fill="${c}" stroke="#23304a" stroke-width="2.5"/>`};
const shapeName={circle:'hình tròn',square:'hình vuông',triangle:'hình tam giác',star:'hình ngôi sao'};
function svg(w,h,b,cls='diagram'){return `<svg class="${cls}" viewBox="0 0 ${w} ${h}" role="img">${b}</svg>`}
function seq(items){return `<div class="sequence">${items.join('　→　')}</div>`}
function shapeSeq(items){return svg(Math.max(320,items.length*66+15),86,items.map((x,i)=>`<g transform="translate(${38+i*66} 43)">${x}</g>`).join(''))}
function patternShapes(arr,withQ=true){let xs=arr.map(x=>shape[x.shape](x.color));if(withQ)xs.push(`<text x="0" y="10" text-anchor="middle" font-size="34" font-weight="900">?</text>`);return shapeSeq(xs)}
function matrix(values,missingR,missingC,cell=60){let n=values.length,b='';for(let r=0;r<n;r++)for(let c=0;c<n;c++){let x=c*cell,y=r*cell,v=values[r][c];b+=`<rect x="${x}" y="${y}" width="${cell}" height="${cell}" rx="6" fill="${r===missingR&&c===missingC?'#fff1c7':'#f7f9fd'}" stroke="#23304a" stroke-width="2"/>`;if(v!=='?')b+=`<text x="${x+cell/2}" y="${y+cell/2+9}" text-anchor="middle" font-size="22" font-weight="800">${esc(v)}</text>`;else b+=`<text x="${x+cell/2}" y="${y+cell/2+10}" text-anchor="middle" font-size="30" font-weight="900">?</text>`}return svg(n*cell,n*cell,b)}
function cube(x,y,fill='#6d9df5'){let s=42,dx=26,dy=15;return `<g><polygon points="${x},${y} ${x+dx},${y-dy} ${x+dx+s},${y} ${x+s},${y+dy}" fill="#9fc1ff" stroke="#23304a" stroke-width="2"/><polygon points="${x},${y} ${x+s},${y+dy} ${x+s},${y+dy+s} ${x},${y+s}" fill="${fill}" stroke="#23304a" stroke-width="2"/><polygon points="${x+s},${y+dy} ${x+dx+s},${y} ${x+dx+s},${y+s} ${x+s},${y+dy+s}" fill="#4f78c7" stroke="#23304a" stroke-width="2"/></g>`}
function cubeStack(heights){let b='',baseY=190;for(let c=0;c<heights.length;c++)for(let z=0;z<heights[c];z++){let x=55+c*70-z*18,y=baseY-z*52;b+=cube(x,y,c%2?'#6d9df5':'#62b38c')}return svg(Math.max(330,heights.length*72+100),235,b,'cube-diagram')}
function picture(items){return `<div class="visual-text">${items.join('　')}</div>`}
function numberQ(l,r){
 if(l<=2){let d=l,s=ri(r,1,8),a=[s,s+d,s+2*d,s+3*d],ans=s+4*d;return Q('Số nào tiếp theo?',ans,choices(r,ans,d,0,30),seq([...a,'<strong>?</strong>']),`Mỗi bước tăng ${d}.`)}
 if(l===3){let d=ri(r,1,3),s=ri(r,10,20),a=[s,s-d,s-2*d,s-3*d],ans=s-4*d;return Q('Số nào tiếp theo?',ans,choices(r,ans,d,0,30),seq([...a,'<strong>?</strong>']),`Mỗi bước giảm ${d}.`)}
 if(l===4){let x=ri(r,1,6),a=[x,x+2,x+1,x+3,x+2,x+4],ans=x+3;return Q('Số nào tiếp theo theo quy luật xen kẽ?',ans,choices(r,ans,1,0,30),seq([...a,'<strong>?</strong>']),'Các bước lặp lại: +2, −1, +2, −1...')}
 if(l===5){let x=ri(r,1,3),a=[x,x+1,x+3,x+6,x+10],ans=x+15;return Q('Số nào tiếp theo?',ans,choices(r,ans,1,0,30),seq([...a,'<strong>?</strong>']),'Khoảng cách tăng lần lượt +1, +2, +3, +4, +5.')}
 if(l===6){let x=ri(r,12,18),a=[x,x-1,x-3,x-6,x-10],ans=x-15;return Q('Số nào tiếp theo?',ans,choices(r,ans,1,0,30),seq([...a,'<strong>?</strong>']),'Mỗi bước giảm thêm 1: −1, −2, −3, −4, −5.')}
 if(l===7){let a=ri(r,1,3),b=ri(r,2,5),v=[a,b];while(v.length<5)v.push(v.at(-1)+v.at(-2));let ans=v[3]+v[4];return Q('Mỗi số mới bằng tổng hai số đứng ngay trước. Số tiếp theo là?',ans,choices(r,ans,2,0,40),seq([...v,'<strong>?</strong>']),`${v[3]} + ${v[4]} = ${ans}.`)}
 if(l===8){let a=ri(r,1,4),b=ri(r,1,4),v=[a,a+b,b,a+b+b,b+b],ans=a+b+b+b;return Q('Dãy số có hai quy luật đan xen. Số tiếp theo là?',ans,choices(r,ans,1,0,35),seq([...v,'<strong>?</strong>']),'Hai dãy con tăng theo các bước riêng; hãy tách vị trí lẻ và vị trí chẵn để tìm quy luật.')}
 if(l===9){let x=ri(r,1,4),a=[x,x+3,x+2,x+5,x+4,x+7],ans=x+6;return Q('Tìm số tiếp theo theo hai quy luật xen kẽ.',ans,choices(r,ans,1,0,30),seq([...a,'<strong>?</strong>']),'Tách dãy thành hai dãy con: vị trí lẻ và vị trí chẵn.')}
 let a=ri(r,1,5),b=a+ri(r,1,3),c=b+ri(r,1,3),ans=a+b+c;return Q(`An có ${a}, Bình có ${b}, Chi có ${c}. Cộng ba số này được bao nhiêu?`,ans,choices(r,ans,1,0,30),picture([`An: ${a}`,`Bình: ${b}`,`Chi: ${c}`]),`${a} + ${b} + ${c} = ${ans}.`)
}
function shapeQ(l,r){let types=['circle','square','triangle','star'];
 if(l<=2){let base=l===1?['circle','square']:['circle','triangle','square'],n=6+ri(r,0,1),a=Array.from({length:n},(_,i)=>({shape:base[i%base.length]})),ans=base[n%base.length];return Q('Hình nào tiếp theo?',shapeName[ans],['hình tròn','hình vuông','hình tam giác','hình ngôi sao'],patternShapes(a),`Mẫu hình lặp lại theo chu kỳ ${base.length}.`)}
 if(l===3){let base=['circle','circle','square','circle','circle','square'],ans='circle';return Q('Hình nào tiếp theo?',shapeName[ans],['hình tròn','hình vuông','hình tam giác','hình ngôi sao'],patternShapes(base.map(s=>({shape:s}))), 'Cứ 2 hình tròn lại đến 1 hình vuông.')}
 if(l===4){let colors=['red','blue','green'],a=Array.from({length:7},(_,i)=>({shape:'circle',color:palette[colors[i%3]]})),ans=colors[7%3];return Q('Màu nào tiếp theo?',({red:'đỏ',blue:'xanh dương',green:'xanh lá'})[ans],['đỏ','xanh dương','xanh lá','vàng'],patternShapes(a), 'Màu lặp theo chu kỳ đỏ → xanh dương → xanh lá.')}
 if(l===5){let a=['circle','square','triangle','star','circle','square','triangle'],ans='star';return Q('Hình nào tiếp theo?',shapeName[ans],types.map(x=>shapeName[x]),patternShapes(a.map(s=>({shape:s}))), 'Chu kỳ 4 hình: tròn → vuông → tam giác → ngôi sao.')}
 if(l===6){let counts=[1,2,3,4,5],ans=6;return Q('Nhóm tiếp theo có bao nhiêu hình tròn?',ans,['4','5','6','7'],picture(counts.map(n=>`● × ${n}`)), 'Mỗi nhóm thêm 1 hình tròn.')}
 if(l===7){let dirs=['↑','→','↓','←'],a=Array.from({length:7},(_,i)=>dirs[i%4]),ans='←';return Q('Mũi tên nào tiếp theo?',ans,dirs,seq([...a,'<strong>?</strong>']),'Mũi tên xoay 90° theo chiều kim đồng hồ ở mỗi bước.')}
 if(l===8){let pairs=[['circle','red'],['square','blue'],['circle','blue'],['square','red']],a=Array.from({length:7},(_,i)=>({shape:pairs[i%4][0],color:palette[pairs[i%4][1]]})),p=pairs[7%4],ans=`${shapeName[p[0]]} ${p[1]==='red'?'đỏ':'xanh dương'}`;return Q('Cặp hình nào tiếp theo?',ans,pairs.map(x=>`${shapeName[x[0]]} ${x[1]==='red'?'đỏ':'xanh dương'}`),patternShapes(a),'Hình dạng và màu sắc cùng lặp theo chu kỳ 4.')}
 if(l===9){let a=[['circle','red'],['square','blue'],['triangle','green'],['circle','blue'],['square','green'],['triangle','red'],['circle','green']],ans='hình vuông đỏ';return Q('Hình nào còn thiếu để hoàn thành quy luật?',ans,['hình vuông đỏ','hình tam giác xanh dương','hình tròn vàng','hình vuông xanh dương'],patternShapes(a.map(x=>({shape:x[0],color:palette[x[1]]}))), 'Trong chu kỳ, mỗi hình xuất hiện với các màu khác nhau; vị trí tiếp theo là hình vuông màu đỏ.')}
 let a=[{shape:'circle',color:palette.red},{shape:'square',color:palette.blue},{shape:'triangle',color:palette.green},{shape:'circle',color:palette.blue},{shape:'square',color:palette.green}],ans='hình tam giác đỏ';return Q('Hình nào tiếp theo khi cả hình dạng và màu đều dịch chuyển?',ans,['hình tam giác đỏ','hình tròn đỏ','hình vuông đỏ','hình tam giác vàng'],patternShapes(a),'Hình dạng lặp tròn → vuông → tam giác; màu dịch đỏ → xanh dương → xanh lá.')
}
function logicQ(l,r){const names=['An','Bình','Chi','Dũng'];
 if(l<=2){let a=ri(r,2,6),b=a+ri(r,1,3);return Q(`${names[0]} có ${a} viên bi. ${names[1]} có ${b} viên bi. Ai có nhiều hơn?`,names[1],[names[0],names[1],'Hai bạn bằng nhau','Không đủ thông tin'],picture([`${names[0]}: ${'🔵'.repeat(a)}`,`${names[1]}: ${'🔵'.repeat(b)}`]),`${b} lớn hơn ${a}.`)}
 if(l===3){let p=shuffle(r,names.slice(0,3));return Q(`${p[0]} đứng trước ${p[1]}. ${p[1]} đứng trước ${p[2]}. Ai đứng cuối?`,p[2],p.slice(0,3).concat('Không xác định'),seq([p[0],p[1],'?']),`${p[2]} đứng sau ${p[1]}.`)}
 if(l===4){let x=ri(r,2,5),order=shuffle(r,['An','Bình','Chi']);return Q(`${order[0]} có ${x} quả. ${order[1]} có nhiều hơn ${order[0]} 2 quả. ${order[2]} có ít hơn ${order[1]} 1 quả. Ai có nhiều nhất?`,order[1],['An','Bình','Chi','Bằng nhau'],picture([`${order[0]}: ${x}`,`${order[1]}: ${x+2}`,`${order[2]}: ${x+1}`]),`${order[1]} có ${x+2}, lớn nhất.`)}
 if(l===5){let colors=['đỏ','xanh','vàng'],b=pick(r,colors),c=pick(r,colors.filter(x=>x!==b)),ans=colors.find(x=>x!==b&&x!==c);return Q(`Ba hộp có màu đỏ, xanh và vàng. Hộp B màu ${b}. Hộp C không màu ${b} và cũng không màu ${c}. Hộp C màu gì?`,ans,colors.concat('không xác định'),picture([`B = ${b}`,`C ≠ ${b}`,`C ≠ ${c}`]),`C chỉ còn màu ${ans}.`)}
 if(l===6){let b=ri(r,3,6),a=b-1,c=ri(r,2,b-1);return Q(`An có ít hơn Bình 1 viên. Chi có ít hơn Bình. Ai có nhiều nhất?`,'Bình',['An','Bình','Chi','Không xác định'],picture([`An: ${a}`,`Bình: ${b}`,`Chi: ${c}`]),`An < Bình và Chi < Bình nên Bình có nhiều nhất.`)}
 if(l<=8){let order=shuffle(r,names),first=order[0],last=order[3];return Q(`Bốn bạn ${names.join(', ')} xếp hàng. ${first} đứng đầu. ${last} đứng cuối. ${order[1]} đứng trước ${order[2]}. Ai đứng vị trí thứ 2?`,order[1],names,picture([`1. ${first}`,`2. ?`,`3. ${order[2]}`,`4. ${last}`]),`Sau ${first}, ${order[1]} phải đứng trước ${order[2]}, nên vị trí 2 là ${order[1]}.`)}
 if(l===9){return Q('Có 3 hộp A, B, C. A không đỏ. B không xanh. C màu vàng. Nếu mỗi màu đỏ, xanh, vàng chỉ dùng một lần, A màu gì?','xanh',['đỏ','xanh','vàng','Không xác định'],picture(['A ≠ đỏ','B ≠ xanh','C = vàng']), 'Vàng đã dùng cho C; A không đỏ nên A phải là xanh.')}
 let a=ri(r,2,5),b=a+1,c=b+1,d=ri(r,1,a-1);return Q(`An có ${a} viên. Bình có nhiều hơn An 1 viên. Chi có nhiều hơn Bình 1 viên. Dũng có ${d} viên. Ai có ít nhất?`,'Dũng',['An','Bình','Chi','Dũng'],picture([`An: ${a}`,`Bình: ${b}`,`Chi: ${c}`,`Dũng: ${d}`]),`Dũng có ${d}, ít hơn An có ${a}.`)
}
function matrixQ(l,r){
 if(l<=2){let a=ri(r,1,4),b=ri(r,1,4),g=[[a,b,a+b],[b,a,a+b],[a,b,'?']];return Q('Số nào còn thiếu?',a+b,choices(r,a+b,1,0,20),matrix(g,2,2),`Ô còn thiếu bằng tổng ${a} + ${b} = ${a+b}.`)}
 if(l===3){let base=ri(r,1,4),g=Array.from({length:3},(_,rr)=>Array.from({length:3},(_,cc)=>base+rr+cc));let ans=base+4;g[2][2]='?';return Q('Mỗi bước sang phải hoặc xuống tăng 1. Số nào còn thiếu?',ans,choices(r,ans,1,0,15),matrix(g,2,2),'Mỗi lần sang phải hoặc xuống tăng 1; ô cuối cách ô đầu 4 bước.')}
 if(l===4){let a=ri(r,1,3),g=[[a,a+1,a+2],[a+1,a+2,a+3],[a+2,a+3,'?']];let ans=a+4;return Q('Mỗi hàng và cột tăng 1. Số nào còn thiếu?',ans,choices(r,ans,1,0,12),matrix(g,2,2),'Cả theo hàng và theo cột đều tăng 1.')}
 if(l===5){let g=[[1,2,3],[2,3,1],[3,1,'?']];return Q('Mỗi hàng và mỗi cột đều có đủ 1, 2, 3. Số nào còn thiếu?','2',['1','2','3','4'],matrix(g,2,2),'Hàng cuối phải là 3, 1, 2.')}
 if(l===6){let x=ri(r,1,4),g=[[x,x+1,x+2],[x+1,x+2,x+3],[x+2,x+3,'?']];return Q('Tìm số còn thiếu theo quy luật đồng thời của hàng và cột.',x+4,choices(r,x+4,1,0,15),matrix(g,2,2),'Mỗi bước sang phải hoặc xuống tăng 1.')}
 if(l===7){let a=ri(r,1,3),g=Array.from({length:4},(_,rr)=>Array.from({length:4},(_,cc)=>a+rr+cc));let ans=a+6;g[3][3]='?';return Q('Ma trận 4×4: sang phải hoặc xuống tăng 1. Số nào còn thiếu?',ans,choices(r,ans,1,0,15),matrix(g,3,3,52),'Ô cuối cách ô đầu 6 bước.')}
 if(l===8){let g=[['🔴','🔵','🟢'],['🔵','🟢','🔴'],['🟢','🔴','?']];return Q('Mỗi hàng và cột đều có đủ 3 màu. Ô còn thiếu là màu gì?','🔵',['🔴','🔵','🟢','🟡'],matrix(g,2,2),'Hàng cuối cần xanh dương để đủ ba màu.')}
 if(l===9){let g=[[1,2,4],[2,4,8],[4,8,'?']];return Q('Mỗi số sang phải gấp đôi số trước. Ô còn thiếu là?',16,['8','12','16','18'],matrix(g,2,2),'4 → 8 → 16.')}
 let g=[[2,3,5],[3,5,8],[5,8,'?']];return Q('Mỗi ô ở góc dưới bên phải bằng tổng hai số liền kề phía trên và bên trái. Số nào còn thiếu?',13,['10','12','13','15'],matrix(g,2,2),'5 + 8 = 13.')
}
function geoQ(l,r){
 if(l<=2){let k=pick(r,['tam giác','hình vuông','hình chữ nhật']);let sides={'tam giác':3,'hình vuông':4,'hình chữ nhật':4}[k];return Q(`Hình ${k} có bao nhiêu cạnh?`,sides,['3','4','5','6'],picture([k,'Số cạnh: ?']),`Hình ${k} có ${sides} cạnh.`)}
 if(l===3){let a=ri(r,2,5),b=ri(r,1,4),ans=a+b;return Q(`Có ${a} hình tròn và ${b} hình vuông. Có tất cả bao nhiêu hình?`,ans,choices(r,ans,1,0,15),picture([`🔵 × ${a}`,`🟦 × ${b}`]),`${a} + ${b} = ${ans}.`)}
 if(l===4){let a=ri(r,2,4),b=ri(r,2,4),ans=a+b;return Q(`Có ${a} hình tam giác. Số hình vuông nhiều hơn ${a} là ${b}. Có tất cả bao nhiêu hình?`,ans,choices(r,ans,1,0,15),picture([`🔺 × ${a}`,`🟦 × ${a+b}`]),`Số hình vuông = ${a}+${b}=${a+b}; tổng = ${ans}.`)}
 if(l===5){let total=ri(r,6,10),red=ri(r,2,total-2),ans=total-red;return Q(`Có ${total} hình. Trong đó ${red} hình là hình tròn. Còn lại bao nhiêu hình không phải hình tròn?`,ans,choices(r,ans,1,0,15),picture([`Tất cả: ${total}`,`Hình tròn: ${red}`,`Còn lại: ?`]),`${total} − ${red} = ${ans}.`)}
 if(l===6){return Q('Hình dưới được ghép từ 4 hình vuông nhỏ. Có bao nhiêu hình vuông tất cả nếu tính cả hình vuông lớn?','5',['4','5','6','8'],svg(260,150,[0,1].flatMap(rw=>[0,1].map(cl=>`<rect x="${55+cl*50}" y="${25+rw*50}" width="50" height="50" fill="#9ec1ff" stroke="#23304a" stroke-width="3"/>`)).join('')+`<rect x="55" y="25" width="100" height="100" fill="none" stroke="#d83b4b" stroke-width="4"/>`),'4 hình vuông nhỏ + 1 hình vuông lớn = 5.')}
 if(l===7){let a=ri(r,2,4),b=ri(r,2,4),ans=a+b;return Q(`Một hình được tách thành ${a} phần màu đỏ và ${b} phần màu xanh. Có tất cả bao nhiêu phần?`,ans,choices(r,ans,1,0,15),picture([`🔴 × ${a}`,`🔵 × ${b}`]),`${a} + ${b} = ${ans}.`)}
 if(l===8){return Q('Trong hình có bao nhiêu tam giác?','4',['2','3','4','5'],svg(300,190,`<path d="M150 20L260 160H40Z" fill="#fff3c4" stroke="#23304a" stroke-width="3"/><path d="M150 20V160M40 160H260" stroke="#23304a" stroke-width="3"/><path d="M95 90H205" stroke="#23304a" stroke-width="3"/>`),'Có 3 tam giác nhỏ ở phía trên và 1 tam giác lớn bao quanh = 4.')}
 if(l===9){let a=ri(r,2,4),b=ri(r,2,4),ans=a*b;return Q(`Có ${a} hàng, mỗi hàng có ${b} hình tròn. Có tất cả bao nhiêu hình tròn?`,ans,choices(r,ans,1,0,20),picture(Array.from({length:a},()=>`● `.repeat(b))),`${a} × ${b} = ${ans}.`)}
 return Q('Một hình vuông được chia thành 4 hình vuông nhỏ. Nếu ghép 4 hình nhỏ lại, ta có bao nhiêu hình vuông có thể đếm được?','5',['4','5','6','8'],svg(250,150,`<rect x="55" y="25" width="100" height="100" fill="#e9f2ff" stroke="#23304a" stroke-width="3"/><path d="M105 25V125M55 75H155" stroke="#23304a" stroke-width="3"/>`),'Có 4 hình vuông nhỏ và 1 hình vuông lớn = 5.')
}
function spaceQ(l,r){
 if(l<=2){let n=ri(r,2,5),h=Array.from({length:n},()=>1);return Q('Có tất cả bao nhiêu khối lập phương trong hình?',n,choices(r,n,1,0,9),cubeStack(h),`Có ${n} khối lập phương.`)}
 if(l<=4){let h=Array.from({length:ri(r,3,4)},()=>ri(r,1,l));let ans=h.reduce((a,b)=>a+b,0);return Q('Đếm tất cả các khối lập phương trong mô hình.',ans,choices(r,ans,1,0,20),cubeStack(h),`Cộng số khối ở từng cột: ${h.join(' + ')} = ${ans}.`)}
 if(l===5){let h=[1,2,1,ri(r,2,3)];return Q('Cột nào có nhiều khối nhất?',String(h.indexOf(Math.max(...h))+1),['1','2','3','4'],cubeStack(h),`Cột ${h.indexOf(Math.max(...h))+1} có ${Math.max(...h)} khối, nhiều nhất.`)}
 if(l===6){let h=[ri(r,1,2),ri(r,2,3),ri(r,1,2)],ans=h[0]+h[2];return Q('Nếu bỏ cột giữa, còn lại bao nhiêu khối?',ans,choices(r,ans,1,0,10),cubeStack(h),`Bỏ cột giữa: còn ${h[0]} + ${h[2]} = ${ans} khối.`)}
 if(l===7){let h=[1,2,3,2];return Q('Mô hình có 4 cột với số khối lần lượt 1, 2, 3, 2. Có tất cả bao nhiêu khối?',8,['6','7','8','9'],cubeStack(h),'1 + 2 + 3 + 2 = 8.')}
 if(l===8){return Q('Một khối có mặt trước là 4, mặt phải là 1, mặt trên là 6. Khi xoay khối sang phải 90°, mặt nào ra phía trước?','1',['1','2','4','6'],svg(300,190,`<g transform="translate(70 90)">${cube(0,0,'#6d9df5')}<text x="21" y="-23" font-size="18" font-weight="900">6</text><text x="73" y="34" font-size="18" font-weight="900">1</text><text x="21" y="36" font-size="18" font-weight="900" fill="#fff">4</text></g>`),'Khi xoay sang phải 90°, mặt phải cũ chuyển ra phía trước.')}
 if(l===9){let h=[2,1,3,2,1];return Q('Có 5 cột khối. Đếm tất cả các khối, kể cả cột phía sau.',9,choices(r,9,1,0,15),cubeStack(h),'2 + 1 + 3 + 2 + 1 = 9.')}
 let h=[1,3,2,3];return Q('Hai cột cao nhất có 3 khối. Tổng số khối của mô hình là bao nhiêu?',9,['7','8','9','10'],cubeStack(h),'1 + 3 + 2 + 3 = 9.')
}
function observeQ(l,r){
 if(l<=2){let a=ri(r,2,6),b=ri(r,1,4);return Q(`Có ${a} quả táo và ${b} quả cam. Có tất cả bao nhiêu quả?`,a+b,choices(r,a+b,1,0,15),picture([`🍎 × ${a}`,`🍊 × ${b}`]),`${a} + ${b} = ${a+b}.`)}
 if(l===3){let total=ri(r,7,12),eaten=ri(r,2,5);return Q(`Có ${total} chiếc bánh. Bé ăn ${eaten} chiếc. Còn lại bao nhiêu chiếc?`,total-eaten,choices(r,total-eaten,1,0,15),picture([`🍪 × ${total}`,`Ăn: ${eaten}`,`Còn: ?`]),`${total} − ${eaten} = ${total-eaten}.`)}
 if(l===4){let a=ri(r,2,5),b=a+ri(r,1,3);return Q(`Trong tranh có ${a} quả táo và ${b} quả cam. Loại nào nhiều hơn?`,'quả cam',['quả táo','quả cam','bằng nhau','không biết'],picture([`🍎 × ${a}`,`🍊 × ${b}`]),`${b} > ${a} nên quả cam nhiều hơn.`)}
 if(l===5){let red=ri(r,2,4),blue=ri(r,2,4),green=ri(r,1,3),ans=red+green;return Q(`Có ${red} quả màu đỏ, ${blue} quả màu xanh dương và ${green} quả màu xanh lá. Có bao nhiêu quả không màu xanh dương?`,ans,choices(r,ans,1,0,15),picture([`🔴 ${red}`,`🔵 ${blue}`,`🟢 ${green}`]),`Không xanh dương = ${red} + ${green} = ${ans}.`)}
 if(l===6){let a=ri(r,2,5),b=ri(r,2,5),c=ri(r,1,3),ans=a+b-c;return Q(`Có ${a} con chim trên cây. Có thêm ${b} con bay đến, sau đó ${c} con bay đi. Còn lại bao nhiêu con?`,ans,choices(r,ans,1,0,15),picture([`🐦 ${a}`,`+ ${b}`,`− ${c}`]),`${a} + ${b} − ${c} = ${ans}.`)}
 if(l===7){let total=ri(r,8,12),red=ri(r,2,4),blue=ri(r,2,4);if(red+blue>=total){red=2;blue=2}let ans=total-red-blue;return Q(`Có ${total} chiếc kẹo. ${red} chiếc đỏ và ${blue} chiếc xanh. Số còn lại màu vàng. Có bao nhiêu chiếc vàng?`,ans,choices(r,ans,1,0,15),picture([`Tất cả: ${total}`,`Đỏ: ${red}`,`Xanh: ${blue}`,`Vàng: ?`]),`${total} − ${red} − ${blue} = ${ans}.`)}
 if(l===8){let rows=ri(r,2,4),each=ri(r,2,4),ans=rows*each;return Q(`Có ${rows} hàng, mỗi hàng ${each} chiếc ghế. Có tất cả bao nhiêu chiếc ghế?`,ans,choices(r,ans,1,0,20),picture(Array.from({length:rows},(_,i)=>`Hàng ${i+1}: 🪑 × ${each}`)),`${rows} × ${each} = ${ans}.`)}
 if(l===9){let a=ri(r,3,5),b=ri(r,2,4),c=ri(r,1,3),ans=a+b+c;return Q(`Ba giỏ có lần lượt ${a}, ${b}, ${c} quả. Lấy ra 1 quả từ mỗi giỏ. Còn lại bao nhiêu quả?`,ans-3,choices(r,ans-3,1,0,15),picture([`Giỏ 1: ${a}`,`Giỏ 2: ${b}`,`Giỏ 3: ${c}`,`Lấy 1 từ mỗi giỏ`]),`${a}+${b}+${c}=${ans}; lấy 3 quả nên còn ${ans-3}.`)}
 let ar=ri(r,3,5),br=ri(r,2,4),cr=ri(r,2,3);return Q(`Có ${ar} bông đỏ, ${br} bông vàng và ${cr} bông xanh. Bỏ tất cả bông vàng. Còn bao nhiêu bông?`,ar+cr,choices(r,ar+cr,1,0,15),picture([`🔴 ${ar}`,`🟡 ${br}`,`🔵 ${cr}`]),`Không tính bông vàng: ${ar} + ${cr} = ${ar+cr}.`)
}
function challengeQ(l,r){let types=[()=>numberQ(Math.min(10,l),r),()=>shapeQ(Math.min(10,l),r),()=>logicQ(Math.min(10,l),r),()=>matrixQ(Math.min(10,l),r),()=>geoQ(Math.min(10,l),r),()=>spaceQ(Math.min(10,l),r),()=>observeQ(Math.min(10,l),r)];return pick(r,types)()}
const generators={'quy-luat-so':numberQ,'quy-luat-hinh':shapeQ,logic:logicQ,'hinh-hoc':geoQ,'bang-so':matrixQ,'khong-gian':spaceQ,'quan-sat':observeQ,'thu-thach':challengeQ};
let level=Number(new URLSearchParams(location.search).get('level')||1);if(level<1||level>10)level=1;let seedBase=Date.now()>>>0,questions=[],idx=0,score=0,streak=0,answered=false;
function buildLevel(){questions=[];idx=0;answered=false;let gen=generators[topic]||numberQ,used=new Set(),tries=0;while(questions.length<10&&tries<400){tries++;let r=rng((seedBase+level*10007+tries*7919)>>>0),q;try{q=gen(level,r)}catch(e){continue}let sig=q.question+'|'+q.answer+'|'+q.visual.replace(/\s+/g,'');if(!used.has(sig)){used.add(sig);q.id=`${topic}-${level}-${questions.length+1}-${tries}`;questions.push(q)}}while(questions.length<10){let r=rng((seedBase+questions.length*97)>>>0),q=gen(level,r);q.id=`fallback-${questions.length}`;questions.push(q)}renderQ()}
function renderLevels(){const el=$('#levels');el.innerHTML=LEVELS[3].map((name,i)=>`<button class="${i+1===level?'on':''}" data-level="${i+1}"><strong>${i+1}</strong><small>${esc(name)}</small></button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{level=+b.dataset.level;seedBase=(Date.now()>>>0);score=0;streak=0;renderLevels();buildLevel()})}
function renderQ(){let q=questions[idx];answered=false;$('#qNo').textContent=`Câu ${idx+1}/10`,$('#score').textContent=`⭐ ${score}`,$('#streak').textContent=`🔥 ${streak}`,$('#progress').style.width=`${idx*10}%`,$('#question').innerHTML=esc(q.question),$('#visual').innerHTML=q.visual,$('#feedback').textContent='',$('#explain').classList.remove('show'),$('#explain').textContent=q.explain,$('#hint').onclick=()=>{$('#explain').classList.add('show');$('#feedback').textContent='💡 Hãy tìm đúng quy luật hoặc thông tin quan trọng.'},$('#next').classList.remove('show');let opts=shuffle(rng((seedBase+idx*31337)>>>0),q.options);$('#options').innerHTML=opts.map(o=>`<button class="option" data-answer="${esc(o)}">${o}</button>`).join('');$('#options').querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(b,q))}
function answer(btn,q){if(answered)return;answered=true;let ok=btn.dataset.answer===q.answer;$('#options').querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.answer===q.answer)b.classList.add('correct')});if(ok){score+=10+streak*2;streak++;btn.classList.add('correct');$('#feedback').textContent='🎉 Chính xác!'}else{streak=0;btn.classList.add('wrong');$('#feedback').textContent=`Chưa đúng. Đáp án là ${q.answer}.`}$('#score').textContent=`⭐ ${score}`,$('#streak').textContent=`🔥 ${streak}`,$('#explain').classList.add('show'),$('#next').classList.add('show')}
function finish(){localStorage.setItem(`ttd:${topic}:${level}`,String(Math.max(score,Number(localStorage.getItem(`ttd:${topic}:${level}`)||0))));$('#questionCard').innerHTML=`<div class="finish"><div class="big">🏆</div><h2>Hoàn thành Level ${level}!</h2><p>Bé đạt <strong>${score}</strong> điểm sau 10 câu.</p><p>${score>=90?'🌟 Xuất sắc!':score>=70?'👏 Rất tốt!':'💪 Cố gắng thêm một chút nhé!'}</p><button onclick="location.href='ttd-${topic}.html?level=${level}'">🔄 Chơi lại</button><button onclick="location.href='toan-tu-duy.html'">📚 Chọn chủ đề</button></div>`}
function init(){if(!META[topic])return;$('#topicIcon').textContent=META[topic][1];$('#topicTitle').textContent=META[topic][0];$('#topicDesc').textContent=META[topic][2];renderLevels();buildLevel();$('#next').onclick=()=>{if(!answered)return;if(idx<9){idx++;renderQ()}else finish()}}
document.addEventListener('DOMContentLoaded',init);
})();