/* Curated visual-first pilot bank v2.1.
 * Choices may be objects rendered as SVG, not text labels.
 */
const TTD_BANK_V2=(()=>{
 const q=[],A=(id,topic,level,type,kind,data,question,answer,explain,d)=>q.push(TTD_ENGINE_V2.make({id,topic,level,type,problem:{kind,...data},question,answer,explain,distractors:d}));
 const sh=(shape,color)=>({type:'shape',shape,color});
 // Missing shape: visual answer choices.
 A('MSV_001','missing-shape',1,'AB','sequence',{items:[sh('circle','#ef4444'),sh('square','#3b82f6'),sh('circle','#ef4444'),sh('square','#3b82f6')],missing:4,answer:sh('circle','#ef4444')},'Hình nào cần đặt vào ô còn thiếu?',sh('circle','#ef4444'),'Hai hình luân phiên: tròn đỏ, vuông xanh.',[sh('square','#22c55e'),sh('triangle','#f59e0b'),sh('star','#a855f7')]);
 A('MSV_002','missing-shape',2,'ABC','sequence',{items:[sh('triangle','#ef4444'),sh('circle','#22c55e'),sh('star','#f59e0b'),sh('triangle','#ef4444'),sh('circle','#22c55e')],missing:5,answer:sh('star','#f59e0b')},'Hình nào tiếp theo trong quy luật?',sh('star','#f59e0b'),'Chu kỳ gồm tam giác, tròn, sao.',[sh('triangle','#ef4444'),sh('circle','#22c55e'),sh('square','#3b82f6')]);
 A('MSV_003','missing-shape',3,'AAB','sequence',{items:[sh('circle','#f59e0b'),sh('circle','#f59e0b'),sh('square','#3b82f6'),sh('circle','#f59e0b'),sh('circle','#f59e0b')],missing:5,answer:sh('square','#3b82f6')},'Hình nào còn thiếu?',sh('square','#3b82f6'),'Mỗi nhóm có hai hình tròn vàng rồi một hình vuông xanh.',[sh('circle','#f59e0b'),sh('triangle','#ef4444'),sh('diamond','#8b5cf6')]);
 A('MSV_004','missing-shape',4,'rotation','sequence',{items:[sh('triangle','#3b82f6'),sh('triangle','#3b82f6'),sh('diamond','#3b82f6'),sh('diamond','#3b82f6')],missing:4,answer:sh('triangle','#3b82f6')},'Hình nào tiếp theo?',sh('triangle','#3b82f6'),'Hai tam giác rồi hai hình thoi lặp lại.',[sh('diamond','#3b82f6'),sh('circle','#3b82f6'),sh('square','#3b82f6')]);
 A('MSV_005','missing-shape',2,'color','sequence',{items:[sh('circle','#ef4444'),sh('circle','#3b82f6'),sh('circle','#22c55e'),sh('circle','#ef4444'),sh('circle','#3b82f6')],missing:5,answer:sh('circle','#22c55e')},'Hình tiếp theo có màu gì?',sh('circle','#22c55e'),'Màu lặp lại đỏ, xanh dương, xanh lá.',[sh('circle','#ef4444'),sh('circle','#3b82f6'),sh('circle','#f59e0b')]);
 // Shape patterns.
 A('SPV_001','shape-pattern',3,'shape+color','sequence',{items:[sh('circle','#ef4444'),sh('square','#3b82f6'),sh('circle','#22c55e'),sh('circle','#ef4444'),sh('square','#3b82f6')],missing:5,answer:sh('circle','#22c55e')},'Hình tiếp theo là hình nào?',sh('circle','#22c55e'),'Ba cặp hình-màu lặp lại theo thứ tự.',[sh('circle','#ef4444'),sh('square','#22c55e'),sh('triangle','#22c55e')]);
 A('SPV_002','shape-pattern',4,'color+size','sequence',{items:[{type:'shape',shape:'circle',color:'#ef4444',size:'small'},{type:'shape',shape:'circle',color:'#ef4444',size:'large'},{type:'shape',shape:'square',color:'#3b82f6',size:'small'},{type:'shape',shape:'square',color:'#3b82f6',size:'large'}],missing:4,answer:{type:'shape',shape:'circle',color:'#ef4444',size:'small'}},'Hình tiếp theo phải có màu và kích thước nào?',{type:'shape',shape:'circle',color:'#ef4444',size:'small'},'Mỗi hình xuất hiện nhỏ rồi lớn; sau đó chuyển sang hình kế tiếp.',[{type:'shape',shape:'circle',color:'#3b82f6',size:'small'},{type:'shape',shape:'square',color:'#ef4444',size:'large'},{type:'shape',shape:'triangle',color:'#22c55e',size:'small'}]);
 A('SPV_003','shape-pattern',5,'count+color','sequence',{items:[{type:'shape',shape:'circle',color:'#ef4444',count:1},{type:'shape',shape:'circle',color:'#3b82f6',count:2},{type:'shape',shape:'circle',color:'#ef4444',count:3},{type:'shape',shape:'circle',color:'#3b82f6',count:4}],missing:4,answer:{type:'shape',shape:'circle',color:'#ef4444',count:5}},'Nhóm tiếp theo có màu và số lượng như thế nào?',{type:'shape',shape:'circle',color:'#ef4444',count:5},'Màu luân phiên và số lượng tăng thêm một.',[{type:'shape',shape:'circle',color:'#3b82f6',count:5},{type:'shape',shape:'circle',color:'#ef4444',count:4},{type:'shape',shape:'circle',color:'#22c55e',count:6}]);
 A('SPV_004','shape-pattern',6,'three attributes','sequence',{items:[sh('circle','#ef4444'),sh('square','#3b82f6'),sh('triangle','#22c55e'),sh('circle','#ef4444'),sh('square','#3b82f6')],missing:5,answer:sh('triangle','#22c55e')},'Hình tiếp theo là hình nào?',sh('triangle','#22c55e'),'Cả hình và màu cùng đi theo chu kỳ ba bước.',[sh('circle','#3b82f6'),sh('square','#ef4444'),sh('triangle','#f59e0b')]);
 A('SPV_005','shape-pattern',7,'position','sequence',{items:[sh('circle','#ef4444'),sh('square','#3b82f6'),sh('circle','#ef4444'),sh('square','#3b82f6')],missing:4,answer:sh('circle','#ef4444')},'Hình tiếp theo là gì?',sh('circle','#ef4444'),'Hai hình luân phiên.',[sh('square','#3b82f6'),sh('triangle','#22c55e'),sh('diamond','#f59e0b')]);
 // Matrices remain numeric in this first pass; later matrix renderer will become visual-grid aware.
 const M=(id,l,g,r,c,a,e,d)=>A(id,'matrix-reasoning',l,'matrix','matrix',{grid:g,mr:r,mc:c,answer:a},'Điền số còn thiếu trong ma trận. Hãy quan sát hàng và cột.',a,e,d);
 M('MX_001',2,[[1,2,3],[2,3,4],[3,4,5]],1,1,3,'Mỗi bước sang phải hoặc xuống dưới tăng 1.',[2,4,5]);
 M('MX_002',3,[[2,4,6],[4,6,8],[6,8,10]],2,1,8,'Mỗi bước sang phải hoặc xuống dưới tăng 2.',[6,7,9]);
 M('MX_003',4,[[1,2,3],[3,4,5],[5,6,7]],0,2,3,'Mỗi hàng tăng 1; hàng sau bắt đầu hơn hàng trước 2.',[2,4,5]);
 M('MX_004',5,[[1,2,1],[2,1,2],[1,2,1]],2,2,1,'Các số luân phiên 1, 2 theo cả hàng và cột.',[2,3,4]);
 M('MX_005',6,[[2,3,4],[3,4,5],[4,5,6]],1,0,3,'Mỗi hàng sau lớn hơn hàng trước 1.',[2,4,5]);
 const C=(id,l,total,part,a,s='🟦')=>A(id,'shape-composition',l,'missing-piece','compose',{total,part,symbol:s,answer:a},`Hai mảnh tạo thành ${total} ô. Một mảnh có ${part} ô. Mảnh còn thiếu có bao nhiêu ô?`,a,`${total} − ${part} = ${a}.`,[part,total,a+1]);
 C('CP_001',2,6,2,4);C('CP_002',3,7,3,4);C('CP_003',4,9,5,4,'🔺');C('CP_004',5,10,6,4);C('CP_005',6,12,7,5,'🟠');
 const N=(id,l,s,items,a,e,d)=>A(id,'counting-shapes',l,'count','count',{sample:s,items,answer:a},'Có bao nhiêu hình giống hệt hình mẫu?',a,e,d);
 N('CT_001',1,'🔵',['🔴','🔵','🟢','🔵','🟡'],2,'Có hai hình tròn xanh.',[1,3,4]);N('CT_002',2,'🔺',['🔺','🟦','🔺','🔺','🟢','🟦'],3,'Có ba hình tam giác.',[2,4,5]);N('CT_003',3,'⭐',['⭐','🔵','⭐','🔺','🔵','⭐','🔴'],3,'Có ba ngôi sao.',[2,4,5]);N('CT_004',4,'🟦',['🟦','🟦','🔺','🟦','🔴','🔺','🟦'],4,'Có bốn hình vuông xanh.',[3,5,6]);N('CT_005',5,'●',['●','■','●','▲','■','●','◆','●'],4,'Có bốn hình tròn.',[3,5,6]);
 const L=(id,l,question,entities,a,e,d)=>A(id,'multi-condition-logic',l,'constraints','logic',{entities,answer:a},question,a,e,d);
 L('LG_001',4,'An cao hơn Bình. Bình cao hơn Chi. Ai thấp hơn Bình?',['An','Bình','Chi'],'Chi','Chi thấp hơn Bình.',['An','Bình','Không biết']);L('LG_002',4,'An đứng trước Bình. Chi đứng sau Bình. Ai đứng giữa An và Chi?',['An','Bình','Chi'],'Bình','Bình đứng giữa.',['An','Chi','Không biết']);L('LG_003',5,'Lan có quả đỏ. Mai có quả xanh. Hoa không có quả đỏ. Ai chắc chắn có quả đỏ?',['Lan','Mai','Hoa'],'Lan','Lan được nêu rõ là có quả đỏ.',['Mai','Hoa','Không biết']);L('LG_004',6,'Nam lớn hơn Minh. Minh lớn hơn An. Ai lớn nhất?',['Nam','Minh','An'],'Nam','Nam > Minh > An.',['Minh','An','Không biết']);L('LG_005',7,'Có 5 quả đỏ và 3 quả xanh. Lấy đi 2 quả đỏ rồi thêm 1 quả xanh. Có tất cả bao nhiêu quả?',['đỏ','xanh'],'7','8 − 2 + 1 = 7.',['6','8','9']);
 const S=(id,l,layers,a,e,d)=>A(id,'spatial-reasoning',l,'cube-stack','spatial',{layers,answer:a},'Mô hình có các tầng khối như hình. Có tất cả bao nhiêu khối lập phương?',a,e,d);
 S('3D_001',2,[3,1],4,'3 + 1 = 4.',['3','5','6']);S('3D_002',3,[4,2],6,'4 + 2 = 6.',['5','7','8']);S('3D_003',4,[4,3,1],8,'4 + 3 + 1 = 8.',['7','9','10']);S('3D_004',5,[5,4,2],11,'5 + 4 + 2 = 11.',['9','10','12']);S('3D_005',6,[6,4,3,1],14,'6 + 4 + 3 + 1 = 14.',['12','13','15']);
 const W=(id,l,icon,initial,actions,a,text,d)=>A(id,'visual-word-problem',l,'story','word',{icon,initial,actions,answer:a},text,a,'Thực hiện lần lượt từng thay đổi theo câu chuyện.',d);
 W('WP_001',1,'🍎',4,[{type:'add',value:2}],6,'Có 4 quả táo, mẹ thêm 2 quả. Có tất cả bao nhiêu quả táo?',[5,7,8]);W('WP_002',2,'🐟',7,[{type:'remove',value:3}],4,'Có 7 con cá, 3 con bơi đi. Còn lại bao nhiêu con cá?',[3,5,6]);W('WP_003',3,'🚗',5,[{type:'add',value:3},{type:'remove',value:2}],6,'Có 5 chiếc xe, thêm 3 chiếc rồi bớt 2 chiếc. Còn bao nhiêu chiếc?',[5,7,8]);W('WP_004',4,'🎈',6,[{type:'remove',value:2},{type:'add',value:3}],7,'Có 6 quả bóng, tặng 2 quả rồi nhận thêm 3 quả. Bây giờ có bao nhiêu quả?',[5,6,8]);W('WP_005',5,'🐰',8,[{type:'remove',value:3},{type:'remove',value:2},{type:'add',value:1}],4,'Có 8 con thỏ, 3 con vào chuồng, 2 con chạy sang vườn rồi 1 con quay lại. Còn ngoài sân bao nhiêu con?',[3,5,6]);
 return q;
})();
