/* Curated pilot bank: 5 validated questions per priority skill. */
const TTD_BANK_V2=(()=>{
 const q=[],A=(id,topic,level,type,kind,data,question,answer,explain,d)=>q.push(TTD_ENGINE_V2.make({id,topic,level,type,problem:{kind,...data},question,answer,explain,distractors:d}));
 A('MS_001','missing-shape',1,'AB','sequence',{items:['🔴','🔵','🔴','🔵'],missing:4,answer:'🔴'},'Hình nào cần đặt vào ô còn thiếu?','🔴','Hai hình luân phiên đỏ, xanh.',['🔵','🟢','⭐']);
 A('MS_002','missing-shape',2,'ABC','sequence',{items:['🔺','🟢','⭐','🔺','🟢'],missing:5,answer:'⭐'},'Hình nào tiếp theo trong quy luật?','⭐','Chu kỳ là 🔺, 🟢, ⭐ rồi lặp lại.',['🔺','🟢','🟦']);
 A('MS_003','missing-shape',3,'AAB','sequence',{items:['🟡','🟡','🔵','🟡','🟡'],missing:5,answer:'🔵'},'Điền hình còn thiếu.','🔵','Mỗi nhóm có hai hình vàng rồi một hình xanh.',['🟡','🔴','⭐']);
 A('MS_004','missing-shape',4,'rotation','sequence',{items:['↑','→','↓','←'],missing:4,answer:'↑'},'Mũi tên tiếp theo là gì?','↑','Mũi tên xoay 90° theo chiều kim đồng hồ.',['→','↓','←']);
 A('MS_005','missing-shape',5,'count','sequence',{items:['🔵×1','🔵×2','🔵×3','🔵×4'],missing:4,answer:'🔵×5'},'Nhóm tiếp theo có bao nhiêu hình tròn xanh?','🔵×5','Số hình tăng thêm 1 ở mỗi bước.',['🔵×3','🔵×4','🔵×6']);
 A('SP_001','shape-pattern',3,'color+size','sequence',{items:['🔴 nhỏ','🔵 lớn','🔴 nhỏ','🔵 lớn'],missing:4,answer:'🔴 nhỏ'},'Hình nào tiếp theo? Hãy chú ý cả màu và kích thước.','🔴 nhỏ','Cặp màu và kích thước lặp lại.',['🔵 nhỏ','🔴 lớn','🔵 lớn']);
 A('SP_002','shape-pattern',4,'shape+color','sequence',{items:['🔴●','🔵■','🟢●','🔴■','🔵●'],missing:5,answer:'🟢■'},'Hình tiếp theo phải có màu và hình nào?','🟢■','Màu theo chu kỳ đỏ, xanh, xanh lá; hình luân phiên tròn, vuông.',['🟢●','🔴■','🔵■']);
 A('SP_003','shape-pattern',5,'count+color','sequence',{items:['🔴×1','🔵×2','🔴×3','🔵×4'],missing:4,answer:'🔴×5'},'Nhóm tiếp theo là gì?','🔴×5','Màu luân phiên và số lượng tăng 1.',['🔵×5','🔴×4','🔵×6']);
 A('SP_004','shape-pattern',6,'three attributes','sequence',{items:['🔴 nhỏ ↑','🔵 lớn →','🟢 nhỏ ↓','🔴 lớn ←'],missing:4,answer:'🔵 nhỏ ↑'},'Tìm hình tiếp theo theo màu, kích thước và hướng.','🔵 nhỏ ↑','Các thuộc tính tiếp tục theo chu kỳ đã quan sát.',['🔴 nhỏ ↑','🔵 lớn →','🟢 lớn ↓']);
 A('SP_005','shape-pattern',7,'position','sequence',{items:['● trái','■ giữa','● phải','■ giữa'],missing:4,answer:'● trái'},'Hình tiếp theo ở vị trí nào?','● trái','Hình tròn đi trái rồi phải; hình vuông luôn ở giữa.',['● phải','■ trái','■ phải']);
 const M=(id,l,g,r,c,a,e,d)=>A(id,'matrix-reasoning',l,'matrix','matrix',{grid:g,mr:r,mc:c,answer:a},'Điền số còn thiếu trong ma trận. Hãy quan sát hàng và cột.',a,e,d);
 M('MX_001',2,[[1,2,3],[2,3,4],[3,4,5]],1,1,3,'Mỗi bước sang phải hoặc xuống dưới tăng 1.',[2,4,5]);
 M('MX_002',3,[[2,4,6],[4,6,8],[6,8,10]],2,1,8,'Mỗi bước sang phải hoặc xuống dưới tăng 2.',[6,7,9]);
 M('MX_003',4,[[1,2,3],[3,4,5],[5,6,7]],0,2,3,'Mỗi hàng tăng 1; hàng sau bắt đầu hơn hàng trước 2.',[2,4,5]);
 M('MX_004',5,[[1,2,1],[2,1,2],[1,2,1]],2,2,1,'Các số luân phiên 1, 2 theo cả hàng và cột.',[2,3,4]);
 M('MX_005',6,[[2,3,4],[3,4,5],[4,5,6]],1,0,3,'Mỗi hàng sau lớn hơn hàng trước 1.',[2,4,5]);
 const C=(id,l,total,part,a,s='🟦')=>A(id,'shape-composition',l,'missing-piece','compose',{total,part,symbol:s,answer:a},`Hai mảnh tạo thành ${total} ô. Một mảnh có ${part} ô. Mảnh còn thiếu có bao nhiêu ô?`,a,`${total} − ${part} = ${a}.`,[part,total,a+1]);
 C('CP_001',2,6,2,4);C('CP_002',3,7,3,4);C('CP_003',4,9,5,4,'🔺');C('CP_004',5,10,6,4);C('CP_005',6,12,7,5,'🟠');
 const N=(id,l,s,items,a,e,d)=>A(id,'counting-shapes',l,'count','count',{sample:s,items,answer:a},'Có bao nhiêu hình giống hệt hình mẫu?',a,e,d);
 N('CT_001',1,'🔵',['🔴','🔵','🟢','🔵','🟡'],2,'Có hai hình tròn xanh.',[1,3,4]);N('CT_002',2,'🔺',['🔺','🟦','🔺','🔺','🟢','🟦'],3,'Có ba hình tam giác.',[2,4,5]);N('CT_003',3,'⭐',['⭐','🔵','⭐','🔺','🔵','⭐','🔴'],3,'Có ba ngôi sao.',[2,4,5]);N('CT_004',4,'🟦',['🟦','🟦','🔺','🟦','🔴','🔺','🟦'],4,'Có bốn hình vuông xanh.',[3,5,6]);N('CT_005',5,'●',['●','■','●','▲','■','●','◆','●'],4,'Có bốn hình tròn.',[3,5,6]);
 const L=(id,l,question,entities,a,e,d)=>A(id,'multi-condition-logic',l,'constraints','logic',{entities,answer:a},question,a,e,d);
 L('LG_001',4,'An cao hơn Bình. Bình cao hơn Chi. Ai thấp hơn Bình?',['An','Bình','Chi'],'Chi','Chi thấp hơn Bình.',['An','Bình','Không biết']);
 L('LG_002',4,'An đứng trước Bình. Chi đứng sau Bình. Ai đứng giữa An và Chi?',['An','Bình','Chi'],'Bình','Bình đứng sau An và trước Chi.',['An','Chi','Không biết']);
 L('LG_003',5,'Lan có quả đỏ. Mai có quả xanh. Hoa không có quả đỏ. Ai chắc chắn có quả đỏ?',['Lan','Mai','Hoa'],'Lan','Điều kiện nói trực tiếp Lan có quả đỏ.',['Mai','Hoa','Không biết']);
 L('LG_004',6,'Nam lớn hơn Minh. Minh lớn hơn An. Ai lớn nhất?',['Nam','Minh','An'],'Nam','Nam > Minh > An.',['Minh','An','Không biết']);
 L('LG_005',7,'Có 5 quả đỏ và 3 quả xanh. Lấy đi 2 quả đỏ rồi thêm 1 quả xanh. Có tất cả bao nhiêu quả?',['đỏ','xanh'],'7','8 − 2 + 1 = 7.',['6','8','9']);
 const S=(id,l,layers,a,e,d)=>A(id,'spatial-reasoning',l,'cube-stack','spatial',{layers,answer:a},'Mô hình có các tầng khối như hình. Có tất cả bao nhiêu khối lập phương?',a,e,d);
 S('3D_001',2,[3,1],4,'3 + 1 = 4.',['3','5','6']);S('3D_002',3,[4,2],6,'4 + 2 = 6.',['5','7','8']);S('3D_003',4,[4,3,1],8,'4 + 3 + 1 = 8.',['7','9','10']);S('3D_004',5,[5,4,2],11,'5 + 4 + 2 = 11.',['9','10','12']);S('3D_005',6,[6,4,3,1],14,'6 + 4 + 3 + 1 = 14.',['12','13','15']);
 const W=(id,l,icon,initial,actions,a,text,d)=>A(id,'visual-word-problem',l,'story','word',{icon,initial,actions,answer:a},text,a,'Thực hiện lần lượt từng thay đổi theo câu chuyện.',d);
 W('WP_001',1,'🍎',4,[{type:'add',value:2}],6,'Có 4 quả táo, mẹ thêm 2 quả. Có tất cả bao nhiêu quả táo?',[5,7,8]);W('WP_002',2,'🐟',7,[{type:'remove',value:3}],4,'Có 7 con cá, 3 con bơi đi. Còn lại bao nhiêu con cá?',[3,5,6]);W('WP_003',3,'🚗',5,[{type:'add',value:3},{type:'remove',value:2}],6,'Có 5 chiếc xe, thêm 3 chiếc rồi bớt 2 chiếc. Còn bao nhiêu chiếc?',[5,7,8]);W('WP_004',4,'🎈',6,[{type:'remove',value:2},{type:'add',value:3}],7,'Có 6 quả bóng, tặng 2 quả rồi nhận thêm 3 quả. Bây giờ có bao nhiêu quả?',[5,6,8]);W('WP_005',5,'🐰',8,[{type:'remove',value:3},{type:'remove',value:2},{type:'add',value:1}],4,'Có 8 con thỏ, 3 con vào chuồng, 2 con chạy sang vườn rồi 1 con quay lại. Còn ngoài sân bao nhiêu con?',[3,5,6]);
 return q;
})();
